import type { Metadata } from "next";
import LegalPage from "../legal/legal-page";
import { legalConfig } from "../legal/legal-config";

export const metadata: Metadata = { title: "Política de privacidad — PasáLista", description: "Cómo PasáLista trata y protege los datos personales." };

export default function PrivacyPage() {
  return <LegalPage title="Política de privacidad" summary={`Última actualización: ${legalConfig.updatedAt}. Acá explicamos qué datos usamos, para qué y cómo podés ejercer tus derechos.`}>
    <section><h2>1. Responsable</h2><p>El responsable de los datos de la cuenta es {legalConfig.name}, {legalConfig.taxId}, con domicilio en {legalConfig.address}. El canal para privacidad es <a href={`mailto:${legalConfig.privacyEmail}`}>{legalConfig.privacyEmail}</a>.</p></section>
    <section><h2>2. Datos que tratamos</h2><ul><li>Datos de cuenta e identidad, como nombre, email e identificador de autenticación.</li><li>Datos del negocio, catálogo, archivos importados, logo, precios y configuración.</li><li>Datos de pedidos y clientes que el comercio recibe: nombre, teléfono, dirección, observaciones y detalle del pedido.</li><li>Datos de suscripción, estado del plan e identificadores de Mercado Pago. No almacenamos el número completo de tarjeta.</li><li>Datos técnicos y de seguridad, como dirección IP, navegador, registros de errores e intentos de uso.</li></ul></section>
    <section><h2>3. Para qué los usamos</h2><p>Usamos los datos para crear y proteger cuentas; publicar catálogos; procesar pedidos; prestar soporte; gestionar pruebas, planes y cobros; prevenir fraude y abuso; cumplir obligaciones legales; y mantener o mejorar el funcionamiento del servicio.</p></section>
    <section><h2>4. Rol respecto de los clientes del comercio</h2><p>El comercio decide qué datos solicita a sus compradores y con qué finalidad. Para esos datos, el comercio actúa como responsable y PasáLista los procesa por su cuenta para prestar el servicio. El comercio debe informar a sus clientes y contar con una base legal adecuada para ese tratamiento.</p></section>
    <section><h2>5. Proveedores</h2><p>Podemos compartir los datos estrictamente necesarios con proveedores que nos ayudan a operar: Clerk para autenticación, Cloudflare para infraestructura y almacenamiento, Mercado Pago para cobros y WhatsApp cuando el usuario decide abrir esa aplicación. Cada proveedor trata información bajo sus propias condiciones y medidas de seguridad.</p></section>
    <section><h2>6. Transferencias y ubicación</h2><p>Algunos proveedores pueden procesar información fuera de Argentina. En esos casos procuramos utilizar proveedores reconocidos y mecanismos contractuales o legales adecuados para proteger los datos.</p></section>
    <section><h2>7. Conservación</h2><p>Conservamos la información mientras la cuenta esté activa y durante el tiempo razonablemente necesario para permitir su recuperación, atender reclamos, prevenir fraude y cumplir obligaciones contables o legales. Una solicitud de supresión puede exceptuar información que debamos conservar por obligación legal o para proteger derechos de terceros.</p></section>
    <section><h2>8. Seguridad</h2><p>Aplicamos controles de acceso por cuenta, validación de permisos, conexiones cifradas, límites antiabuso, separación entre datos estructurados e imágenes y validación de notificaciones de pago. Ningún sistema es infalible; si detectamos un incidente relevante actuaremos para contenerlo y comunicarlo conforme corresponda.</p></section>
    <section><h2>9. Tus derechos</h2><p>Podés solicitar información, acceso, rectificación, actualización o supresión de tus datos escribiendo a <a href={`mailto:${legalConfig.privacyEmail}`}>{legalConfig.privacyEmail}</a> y acreditando razonablemente tu identidad. El derecho de acceso debe responderse dentro de 10 días corridos y las solicitudes de rectificación, actualización o supresión dentro de 5 días hábiles, conforme la Ley 25.326.</p></section>
    <section><h2>10. Almacenamiento local y cookies</h2><p>Usamos tecnologías necesarias para mantener la sesión y recordar preferencias locales, como el estado de interfaz. Los proveedores de autenticación y pago pueden utilizar sus propias cookies necesarias. No usamos los datos del catálogo para publicidad de terceros.</p></section>
    <section><h2>11. Autoridad de control</h2><p>La Agencia de Acceso a la Información Pública es el órgano de control de la Ley 25.326 y recibe consultas o denuncias vinculadas con el ejercicio de derechos sobre datos personales.</p></section>
  </LegalPage>;
}

